# Generated by Django 5.1.4 on 2026-06-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_key_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
