# Generated by Django 5.1.4 on 2026-06-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_assignment_is_key_verified_assignment_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=30, help_text='Standard duration of an appointment in minutes.'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='buffer_time',
            field=models.PositiveIntegerField(default=10, help_text='Rest/buffer time between appointments in minutes.'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedule', to='staff.staff'),
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='staff.doctorschedule')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
