# Generated by Django 5.1.4 on 2026-03-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_doctor'),
        ('staff', '0016_alter_tokenlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='consultationnote',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_note', to='staff.appointment'),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
