# Generated by Django 5.1.4 on 2026-03-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_patient_user_remove_tokenlog_user_and_more'),
        ('records', '0002_alter_healthreport_patient_and_more'),
        ('staff', '0017_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_records', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribing_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='issued_prescriptions', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile'),
        ),
    ]
