# Generated by Django 5.1.4 on 2026-03-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_delete_appointment'),
        ('patients', '0011_remove_patient_user_remove_tokenlog_user_and_more'),
        ('records', '0003_healthreport_uploaded_by_medicalrecord_doctor_and_more'),
        ('staff', '0017_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
